/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TTopicIdIndexImport } from './routes/t/$topicId/index'
import { Route as PmIssueIdIndexImport } from './routes/pm/$issueId/index'
import { Route as CChannelIdIndexImport } from './routes/c/$channelId/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TTopicIdIndexRoute = TTopicIdIndexImport.update({
  id: '/t/$topicId/',
  path: '/t/$topicId/',
  getParentRoute: () => rootRoute,
} as any)

const PmIssueIdIndexRoute = PmIssueIdIndexImport.update({
  id: '/pm/$issueId/',
  path: '/pm/$issueId/',
  getParentRoute: () => rootRoute,
} as any)

const CChannelIdIndexRoute = CChannelIdIndexImport.update({
  id: '/c/$channelId/',
  path: '/c/$channelId/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/c/$channelId/': {
      id: '/c/$channelId/'
      path: '/c/$channelId'
      fullPath: '/c/$channelId'
      preLoaderRoute: typeof CChannelIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/pm/$issueId/': {
      id: '/pm/$issueId/'
      path: '/pm/$issueId'
      fullPath: '/pm/$issueId'
      preLoaderRoute: typeof PmIssueIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/t/$topicId/': {
      id: '/t/$topicId/'
      path: '/t/$topicId'
      fullPath: '/t/$topicId'
      preLoaderRoute: typeof TTopicIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/c/$channelId': typeof CChannelIdIndexRoute
  '/pm/$issueId': typeof PmIssueIdIndexRoute
  '/t/$topicId': typeof TTopicIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c/$channelId': typeof CChannelIdIndexRoute
  '/pm/$issueId': typeof PmIssueIdIndexRoute
  '/t/$topicId': typeof TTopicIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/c/$channelId/': typeof CChannelIdIndexRoute
  '/pm/$issueId/': typeof PmIssueIdIndexRoute
  '/t/$topicId/': typeof TTopicIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/c/$channelId' | '/pm/$issueId' | '/t/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/c/$channelId' | '/pm/$issueId' | '/t/$topicId'
  id: '__root__' | '/' | '/c/$channelId/' | '/pm/$issueId/' | '/t/$topicId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CChannelIdIndexRoute: typeof CChannelIdIndexRoute
  PmIssueIdIndexRoute: typeof PmIssueIdIndexRoute
  TTopicIdIndexRoute: typeof TTopicIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CChannelIdIndexRoute: CChannelIdIndexRoute,
  PmIssueIdIndexRoute: PmIssueIdIndexRoute,
  TTopicIdIndexRoute: TTopicIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/c/$channelId/",
        "/pm/$issueId/",
        "/t/$topicId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/c/$channelId/": {
      "filePath": "c/$channelId/index.tsx"
    },
    "/pm/$issueId/": {
      "filePath": "pm/$issueId/index.tsx"
    },
    "/t/$topicId/": {
      "filePath": "t/$topicId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
