/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CChannelIdIndexImport } from './routes/c/$channelId/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CChannelIdIndexRoute = CChannelIdIndexImport.update({
  id: '/c/$channelId/',
  path: '/c/$channelId/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/c/$channelId/': {
      id: '/c/$channelId/'
      path: '/c/$channelId'
      fullPath: '/c/$channelId'
      preLoaderRoute: typeof CChannelIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/c/$channelId': typeof CChannelIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c/$channelId': typeof CChannelIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/c/$channelId/': typeof CChannelIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/c/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/c/$channelId'
  id: '__root__' | '/' | '/c/$channelId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CChannelIdIndexRoute: typeof CChannelIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CChannelIdIndexRoute: CChannelIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/c/$channelId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/c/$channelId/": {
      "filePath": "c/$channelId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
